title: "Chao's world"
plugins:
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  bibliography: publications.bib
  bibliography_template: pub-item
  sort_by: year
  order: descending
  group_by: year
  group_order: descending
  bibliography_list_tag: div
  bibliography_item_tag: article
  bibliography_item_class: pub-item
  bibliography_list_class: pub-list
